services:
  - type: web
    name: sisabisa
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 24.15.0
      - key: JWT_SECRET
        generateValue: true
